# Generated by Django 2.1.3 on 2018-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_omnie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('adres', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
