# Generated by Django 2.1.3 on 2018-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181128_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='nr_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
